=== damico/tamandare/tamandare/dist/linux/tamandare.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tamandare">
    <xs:complexType>
    <xs:sequence>
    	<xs:element name="header">
    		<xs:complexType>
    			<xs:sequence>
    				<xs:element name="return" >
    					<xs:complexType>
    						<xs:attribute name="code" type="xs:string"	use="required" />
    						<xs:attribute name="message" type="xs:string"	use="required" />
    					</xs:complexType>
    				</xs:element>
    			</xs:sequence>
    			<xs:attribute name="date" type="xs:string"
    				use="required" />
    			<xs:attribute name="type" type="xs:integer"
    				use="required" />
    		</xs:complexType>
    	</xs:element>
    	<xs:element name="body">
    		<xs:complexType>
    		<xs:sequence>
    			<xs:element name="url" minOccurs="0" maxOccurs="1">
    				<xs:complexType>
    					<xs:attribute name="value" type="xs:string"	use="required" />
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="tags" type="xs:string" minOccurs="0" maxOccurs="50"/>
    			<xs:element name="signature" minOccurs="0" maxOccurs="1">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="content"
    							type="xs:string" minOccurs="0" maxOccurs="1">
    						</xs:element>
    					</xs:sequence>
    					<xs:attribute name="type" type="xs:string" use="required" />
    					<xs:attribute name="entity" type="xs:string" use="required" />
    				</xs:complexType>
    			</xs:element>
    		</xs:sequence>	
    		</xs:complexType>
    	</xs:element>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== damico/tamandare/trunk/tamandare/dist/linux/tamandare.xml
<?xml version="1.0" encoding="UTF-8"?>
<tamandare xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tamandare.xsd">
  <header date="" type="0">
    <return code="" message=""/>
  </header>
  <body>
    <url value=""/>
    <tags>tags</tags>
    <signature entity="" type="">
      <content>content</content>
    </signature>
  </body>
</tamandare>
